// Package schema Code generated by swaggo/swag. DO NOT EDIT
package schema

import "github.com/swaggo/swag"

const schemaTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Солопенков Дмитрий",
            "url": "https://t.me/solopenkovdmitriy"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "post": {
                "description": "Добавить задание",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "AddTask",
                "parameters": [
                    {
                        "description": "Тело запроса в формате JSON",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schema.TaskType"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/task/{id}": {
            "get": {
                "description": "Получить задание по id",
                "tags": [
                    "Task"
                ],
                "summary": "GetTask",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/tasks": {
            "get": {
                "description": "Получить все задания",
                "tags": [
                    "Task"
                ],
                "summary": "GetAllTask",
                "responses": {}
            }
        }
    },
    "definitions": {
        "schema.TaskType": {
            "type": "object",
            "properties": {
                "add_time": {
                    "type": "string"
                },
                "dev_time": {
                    "type": "string"
                },
                "mult_time": {
                    "type": "string"
                },
                "sub_time": {
                    "type": "string"
                },
                "task": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Распеределенный калькулятор (Яндекс.Лицей)",
	Description:      "Распределенный ервис для параллельного вычисления арифметических выражений",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  schemaTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
